In [ ]:
import pandas as pd
import os

folder_path = r"Datasets\MultiClinSum\raw"

In [ ]:
leaf_files = []

for current_dir, subdirs, files in os.walk(folder_path):
    if not subdirs:
        for f in files:
            full_path = os.path.join(current_dir, f)
            file_name = full_path.split("\\")[-1]
            print(file_name)
            info_name = file_name.split(".")[0].split("_")
            file_ext = file_name.split(".")[1]
            with open(full_path, "r", encoding="utf-8") as f:
                content = f.read()
                if len(info_name) == 4:
                    result_dict = {"source": info_name[0], "filetype": file_ext, "id": int(info_name[3]), "language": info_name[2], "quality": info_name[1], "isSummary": False, "content": content}
                elif len(info_name) == 5:
                    result_dict = {"source": info_name[0], "filetype": file_ext, "id": int(info_name[3]), "language": info_name[2], "quality": info_name[1], "isSummary": True, "content": content}
                else:
                    result_dict = {"id": int(info_name[3])}
                leaf_files.append(result_dict)
                
df = pd.DataFrame(leaf_files)

multiclinsum_gs_en_1.txt
multiclinsum_gs_en_10.txt
multiclinsum_gs_en_100.txt
multiclinsum_gs_en_101.txt
multiclinsum_gs_en_102.txt
multiclinsum_gs_en_103.txt
multiclinsum_gs_en_104.txt
multiclinsum_gs_en_105.txt
multiclinsum_gs_en_106.txt
multiclinsum_gs_en_107.txt
multiclinsum_gs_en_108.txt
multiclinsum_gs_en_109.txt
multiclinsum_gs_en_11.txt
multiclinsum_gs_en_110.txt
multiclinsum_gs_en_111.txt
multiclinsum_gs_en_112.txt
multiclinsum_gs_en_113.txt
multiclinsum_gs_en_114.txt
multiclinsum_gs_en_115.txt
multiclinsum_gs_en_116.txt
multiclinsum_gs_en_117.txt
multiclinsum_gs_en_118.txt
multiclinsum_gs_en_119.txt
multiclinsum_gs_en_12.txt
multiclinsum_gs_en_120.txt
multiclinsum_gs_en_121.txt
multiclinsum_gs_en_122.txt
multiclinsum_gs_en_123.txt
multiclinsum_gs_en_124.txt
multiclinsum_gs_en_125.txt
multiclinsum_gs_en_126.txt
multiclinsum_gs_en_127.txt
multiclinsum_gs_en_128.txt
multiclinsum_gs_en_129.txt
multiclinsum_gs_en_13.txt
multiclinsum_gs_en_130.txt
multiclinsum_gs_en_131.txt
multiclinsum_gs_en_132.txt
multiclinsum_gs_en_133.txt
multiclinsum_gs_en_134.txt
multiclinsum_gs_en_135.txt
multiclinsum_gs_en_136.txt
multiclinsum_gs_en_137.txt
multiclinsum_gs_en_138.txt
multiclinsum_gs_en_139.txt
multiclinsum_gs_en_14.txt
multiclinsum_gs_en_140.txt
multiclinsum_gs_en_141.txt
multiclinsum_gs_en_142.txt
multiclinsum_gs_en_143.txt
multiclinsum_gs_en_144.txt
multiclinsum_gs_en_145.txt
multiclinsum_gs_en_146.txt
multiclinsum_gs_en_147.txt
multiclinsum_gs_en_148.txt
multiclinsum_gs_en_149.txt
multiclinsum_gs_en_15.txt
multiclinsum_gs_en_150.txt
multiclinsum_gs_en_151.txt
multiclinsum_gs_en_152.txt
multiclinsum_gs_en_153.txt
multiclinsum_gs_en_154.txt
multiclinsum_gs_en_155.txt
multiclinsum_gs_en_156.txt
multiclinsum_gs_en_157.txt
multiclinsum_gs_en_158.txt
multiclinsum_gs_en_159.txt
multiclinsum_gs_en_16.txt
multiclinsum_gs_en_160.txt
multiclinsum_gs_en_161.txt
multiclinsum_gs_en_162.txt
multiclinsum_gs_en_163.txt
multiclinsum_gs_en_164.txt
multiclinsum_gs_en_165.txt
multiclinsum_gs_en_166.txt
multiclinsum_gs_en_167.txt
multiclinsum_gs_en_168.txt
multiclinsum_gs_en_169.txt
multiclinsum_gs_en_17.txt
multiclinsum_gs_en_170.txt
multiclinsum_gs_en_171.txt
multiclinsum_gs_en_172.txt
multiclinsum_gs_en_173.txt
multiclinsum_gs_en_174.txt
multiclinsum_gs_en_175.txt
multiclinsum_gs_en_176.txt
multiclinsum_gs_en_177.txt
multiclinsum_gs_en_178.txt
multiclinsum_gs_en_179.txt
multiclinsum_gs_en_18.txt
multiclinsum_gs_en_180.txt
multiclinsum_gs_en_181.txt
multiclinsum_gs_en_182.txt
multiclinsum_gs_en_183.txt
multiclinsum_gs_en_184.txt
multiclinsum_gs_en_185.txt
multiclinsum_gs_en_186.txt
multiclinsum_gs_en_187.txt
multiclinsum_gs_en_188.txt
multiclinsum_gs_en_189.txt
multiclinsum_gs_en_19.txt
multiclinsum_gs_en_190.txt
multiclinsum_gs_en_191.txt
multiclinsum_gs_en_192.txt
multiclinsum_gs_en_193.txt
multiclinsum_gs_en_194.txt
multiclinsum_gs_en_195.txt
multiclinsum_gs_en_196.txt
multiclinsum_gs_en_197.txt
multiclinsum_gs_en_198.txt
multiclinsum_gs_en_199.txt
multiclinsum_gs_en_2.txt
multiclinsum_gs_en_20.txt
multiclinsum_gs_en_200.txt
multiclinsum_gs_en_201.txt
multiclinsum_gs_en_202.txt
multiclinsum_gs_en_203.txt
multiclinsum_gs_en_204.txt
multiclinsum_gs_en_205.txt
multiclinsum_gs_en_206.txt
multiclinsum_gs_en_207.txt
multiclinsum_gs_en_208.txt
multiclinsum_gs_en_209.txt
multiclinsum_gs_en_21.txt
multiclinsum_gs_en_210.txt
multiclinsum_gs_en_211.txt
multiclinsum_gs_en_212.txt
multiclinsum_gs_en_213.txt
multiclinsum_gs_en_214.txt
multiclinsum_gs_en_215.txt
multiclinsum_gs_en_216.txt
multiclinsum_gs_en_217.txt
multiclinsum_gs_en_218.txt
multiclinsum_gs_en_219.txt
multiclinsum_gs_en_22.txt
multiclinsum_gs_en_220.txt
multiclinsum_gs_en_221.txt
multiclinsum_gs_en_222.txt
multiclinsum_gs_en_223.txt
multiclinsum_gs_en_224.txt
multiclinsum_gs_en_225.txt
multiclinsum_gs_en_226.txt
multiclinsum_gs_en_227.txt
multiclinsum_gs_en_228.txt
multiclinsum_gs_en_229.txt
multiclinsum_gs_en_23.txt
multiclinsum_gs_en_230.txt
multiclinsum_gs_en_231.txt
multiclinsum_gs_en_232.txt
multiclinsum_gs_en_233.txt
multiclinsum_gs_en_234.txt
multiclinsum_gs_en_235.txt
multiclinsum_gs_en_236.txt
multiclinsum_gs_en_237.txt
multiclinsum_gs_en_238.txt
multiclinsum_gs_en_239.txt
multiclinsum_gs_en_24.txt
multiclinsum_gs_en_240.txt
multiclinsum_gs_en_241.txt
multiclinsum_gs_en_242.txt
multiclinsum_gs_en_243.txt
multiclinsum_gs_en_244.txt
multiclinsum_gs_en_245.txt
multiclinsum_gs_en_246.txt
multiclinsum_gs_en_247.txt
multiclinsum_gs_en_248.txt
multiclinsum_gs_en_249.txt
multiclinsum_gs_en_25.txt
multiclinsum_gs_en_250.txt
multiclinsum_gs_en_251.txt
multiclinsum_gs_en_252.txt
multiclinsum_gs_en_253.txt
multiclinsum_gs_en_254.txt
multiclinsum_gs_en_255.txt
multiclinsum_gs_en_256.txt
multiclinsum_gs_en_257.txt
multiclinsum_gs_en_258.txt
multiclinsum_gs_en_259.txt
multiclinsum_gs_en_26.txt
multiclinsum_gs_en_260.txt
multiclinsum_gs_en_261.txt
multiclinsum_gs_en_262.txt
multiclinsum_gs_en_263.txt
multiclinsum_gs_en_264.txt
multiclinsum_gs_en_265.txt
multiclinsum_gs_en_266.txt
multiclinsum_gs_en_267.txt
multiclinsum_gs_en_268.txt
multiclinsum_gs_en_269.txt
multiclinsum_gs_en_27.txt
multiclinsum_gs_en_270.txt
multiclinsum_gs_en_271.txt
multiclinsum_gs_en_272.txt
multiclinsum_gs_en_273.txt
multiclinsum_gs_en_274.txt
multiclinsum_gs_en_275.txt
multiclinsum_gs_en_276.txt
multiclinsum_gs_en_277.txt
multiclinsum_gs_en_278.txt
multiclinsum_gs_en_279.txt
multiclinsum_gs_en_28.txt
multiclinsum_gs_en_280.txt
multiclinsum_gs_en_281.txt
multiclinsum_gs_en_282.txt
multiclinsum_gs_en_283.txt
multiclinsum_gs_en_284.txt
multiclinsum_gs_en_285.txt
multiclinsum_gs_en_286.txt
multiclinsum_gs_en_287.txt
multiclinsum_gs_en_288.txt
multiclinsum_gs_en_289.txt
multiclinsum_gs_en_29.txt
multiclinsum_gs_en_290.txt
multiclinsum_gs_en_291.txt
multiclinsum_gs_en_292.txt
multiclinsum_gs_en_293.txt
multiclinsum_gs_en_294.txt
multiclinsum_gs_en_295.txt
multiclinsum_gs_en_296.txt
multiclinsum_gs_en_297.txt
multiclinsum_gs_en_298.txt
multiclinsum_gs_en_299.txt
multiclinsum_gs_en_3.txt
multiclinsum_gs_en_30.txt
multiclinsum_gs_en_300.txt
multiclinsum_gs_en_301.txt
multiclinsum_gs_en_302.txt
multiclinsum_gs_en_303.txt
multiclinsum_gs_en_304.txt
multiclinsum_gs_en_305.txt
multiclinsum_gs_en_306.txt
multiclinsum_gs_en_307.txt
multiclinsum_gs_en_308.txt
multiclinsum_gs_en_309.txt
multiclinsum_gs_en_31.txt
multiclinsum_gs_en_310.txt
multiclinsum_gs_en_311.txt
multiclinsum_gs_en_312.txt
multiclinsum_gs_en_313.txt
multiclinsum_gs_en_314.txt
multiclinsum_gs_en_315.txt
multiclinsum_gs_en_316.txt
multiclinsum_gs_en_317.txt
multiclinsum_gs_en_318.txt
multiclinsum_gs_en_319.txt
multiclinsum_gs_en_32.txt
multiclinsum_gs_en_320.txt
multiclinsum_gs_en_321.txt
multiclinsum_gs_en_322.txt
multiclinsum_gs_en_323.txt
multiclinsum_gs_en_324.txt
multiclinsum_gs_en_325.txt
multiclinsum_gs_en_326.txt
multiclinsum_gs_en_327.txt
multiclinsum_gs_en_328.txt
multiclinsum_gs_en_329.txt
multiclinsum_gs_en_33.txt
multiclinsum_gs_en_330.txt
multiclinsum_gs_en_331.txt
multiclinsum_gs_en_332.txt
multiclinsum_gs_en_333.txt
multiclinsum_gs_en_334.txt
multiclinsum_gs_en_335.txt
multiclinsum_gs_en_336.txt
multiclinsum_gs_en_337.txt
multiclinsum_gs_en_338.txt
multiclinsum_gs_en_339.txt
multiclinsum_gs_en_34.txt
multiclinsum_gs_en_340.txt
multiclinsum_gs_en_341.txt
multiclinsum_gs_en_342.txt
multiclinsum_gs_en_343.txt
multiclinsum_gs_en_344.txt
multiclinsum_gs_en_345.txt
multiclinsum_gs_en_346.txt
multiclinsum_gs_en_347.txt
multiclinsum_gs_en_348.txt
multiclinsum_gs_en_349.txt
multiclinsum_gs_en_35.txt
multiclinsum_gs_en_350.txt
multiclinsum_gs_en_351.txt
multiclinsum_gs_en_352.txt
multiclinsum_gs_en_353.txt
multiclinsum_gs_en_354.txt
multiclinsum_gs_en_355.txt
multiclinsum_gs_en_356.txt
multiclinsum_gs_en_357.txt
multiclinsum_gs_en_358.txt
multiclinsum_gs_en_359.txt
multiclinsum_gs_en_36.txt
multiclinsum_gs_en_360.txt
multiclinsum_gs_en_361.txt
multiclinsum_gs_en_362.txt
multiclinsum_gs_en_363.txt
multiclinsum_gs_en_364.txt
multiclinsum_gs_en_365.txt
multiclinsum_gs_en_366.txt
multiclinsum_gs_en_367.txt
multiclinsum_gs_en_368.txt
multiclinsum_gs_en_369.txt
multiclinsum_gs_en_37.txt
multiclinsum_gs_en_370.txt
multiclinsum_gs_en_371.txt
multiclinsum_gs_en_372.txt
multiclinsum_gs_en_373.txt
multiclinsum_gs_en_374.txt
multiclinsum_gs_en_375.txt
multiclinsum_gs_en_376.txt
multiclinsum_gs_en_377.txt
multiclinsum_gs_en_378.txt
multiclinsum_gs_en_379.txt
multiclinsum_gs_en_38.txt
multiclinsum_gs_en_380.txt
multiclinsum_gs_en_381.txt
multiclinsum_gs_en_382.txt
multiclinsum_gs_en_383.txt
multiclinsum_gs_en_384.txt
multiclinsum_gs_en_385.txt
multiclinsum_gs_en_386.txt
multiclinsum_gs_en_387.txt
multiclinsum_gs_en_388.txt
multiclinsum_gs_en_389.txt
multiclinsum_gs_en_39.txt
multiclinsum_gs_en_390.txt
multiclinsum_gs_en_391.txt
multiclinsum_gs_en_392.txt
multiclinsum_gs_en_393.txt
multiclinsum_gs_en_394.txt
multiclinsum_gs_en_395.txt
multiclinsum_gs_en_396.txt
multiclinsum_gs_en_397.txt
multiclinsum_gs_en_398.txt
multiclinsum_gs_en_399.txt
multiclinsum_gs_en_4.txt
multiclinsum_gs_en_40.txt
multiclinsum_gs_en_400.txt
multiclinsum_gs_en_401.txt
multiclinsum_gs_en_402.txt
multiclinsum_gs_en_403.txt
multiclinsum_gs_en_404.txt
multiclinsum_gs_en_405.txt
multiclinsum_gs_en_406.txt
multiclinsum_gs_en_407.txt
multiclinsum_gs_en_408.txt
multiclinsum_gs_en_409.txt
multiclinsum_gs_en_41.txt
multiclinsum_gs_en_410.txt
multiclinsum_gs_en_411.txt
multiclinsum_gs_en_412.txt
multiclinsum_gs_en_413.txt
multiclinsum_gs_en_414.txt
multiclinsum_gs_en_415.txt
multiclinsum_gs_en_416.txt
multiclinsum_gs_en_417.txt
multiclinsum_gs_en_418.txt
multiclinsum_gs_en_419.txt
multiclinsum_gs_en_42.txt
multiclinsum_gs_en_420.txt
multiclinsum_gs_en_421.txt
multiclinsum_gs_en_422.txt
multiclinsum_gs_en_423.txt
multiclinsum_gs_en_424.txt
multiclinsum_gs_en_425.txt
multiclinsum_gs_en_426.txt
multiclinsum_gs_en_427.txt
multiclinsum_gs_en_428.txt
multiclinsum_gs_en_429.txt
multiclinsum_gs_en_43.txt
multiclinsum_gs_en_430.txt
multiclinsum_gs_en_431.txt
multiclinsum_gs_en_432.txt
multiclinsum_gs_en_433.txt
multiclinsum_gs_en_434.txt
multiclinsum_gs_en_435.txt
multiclinsum_gs_en_436.txt
multiclinsum_gs_en_437.txt
multiclinsum_gs_en_438.txt
multiclinsum_gs_en_439.txt
multiclinsum_gs_en_44.txt
multiclinsum_gs_en_440.txt
multiclinsum_gs_en_441.txt
multiclinsum_gs_en_442.txt
multiclinsum_gs_en_443.txt
multiclinsum_gs_en_444.txt
multiclinsum_gs_en_445.txt
multiclinsum_gs_en_446.txt
multiclinsum_gs_en_447.txt
multiclinsum_gs_en_448.txt
multiclinsum_gs_en_449.txt
multiclinsum_gs_en_45.txt
multiclinsum_gs_en_450.txt
multiclinsum_gs_en_451.txt
multiclinsum_gs_en_452.txt
multiclinsum_gs_en_453.txt
multiclinsum_gs_en_454.txt
multiclinsum_gs_en_455.txt
multiclinsum_gs_en_456.txt
multiclinsum_gs_en_457.txt
multiclinsum_gs_en_458.txt
multiclinsum_gs_en_459.txt
multiclinsum_gs_en_46.txt
multiclinsum_gs_en_460.txt
multiclinsum_gs_en_461.txt
multiclinsum_gs_en_462.txt
multiclinsum_gs_en_463.txt
multiclinsum_gs_en_464.txt
multiclinsum_gs_en_465.txt
multiclinsum_gs_en_466.txt
multiclinsum_gs_en_467.txt
multiclinsum_gs_en_468.txt
multiclinsum_gs_en_469.txt
multiclinsum_gs_en_47.txt
multiclinsum_gs_en_470.txt
multiclinsum_gs_en_471.txt
multiclinsum_gs_en_472.txt
multiclinsum_gs_en_473.txt
multiclinsum_gs_en_474.txt
multiclinsum_gs_en_475.txt
multiclinsum_gs_en_476.txt
multiclinsum_gs_en_477.txt
multiclinsum_gs_en_478.txt
multiclinsum_gs_en_479.txt
multiclinsum_gs_en_48.txt
multiclinsum_gs_en_480.txt
multiclinsum_gs_en_481.txt
multiclinsum_gs_en_482.txt
multiclinsum_gs_en_483.txt
multiclinsum_gs_en_484.txt
multiclinsum_gs_en_485.txt
multiclinsum_gs_en_486.txt
multiclinsum_gs_en_487.txt
multiclinsum_gs_en_488.txt
multiclinsum_gs_en_489.txt
multiclinsum_gs_en_49.txt
multiclinsum_gs_en_490.txt
multiclinsum_gs_en_491.txt
multiclinsum_gs_en_492.txt
multiclinsum_gs_en_493.txt
multiclinsum_gs_en_494.txt
multiclinsum_gs_en_495.txt
multiclinsum_gs_en_496.txt
multiclinsum_gs_en_497.txt
multiclinsum_gs_en_498.txt
multiclinsum_gs_en_499.txt
multiclinsum_gs_en_5.txt
multiclinsum_gs_en_50.txt
multiclinsum_gs_en_500.txt
multiclinsum_gs_en_501.txt
multiclinsum_gs_en_502.txt
multiclinsum_gs_en_503.txt
multiclinsum_gs_en_504.txt
multiclinsum_gs_en_505.txt
multiclinsum_gs_en_506.txt
multiclinsum_gs_en_507.txt
multiclinsum_gs_en_508.txt
multiclinsum_gs_en_509.txt
multiclinsum_gs_en_51.txt
multiclinsum_gs_en_510.txt
multiclinsum_gs_en_511.txt
multiclinsum_gs_en_512.txt
multiclinsum_gs_en_513.txt
multiclinsum_gs_en_514.txt
multiclinsum_gs_en_515.txt
multiclinsum_gs_en_516.txt
multiclinsum_gs_en_517.txt
multiclinsum_gs_en_518.txt
multiclinsum_gs_en_519.txt
multiclinsum_gs_en_52.txt
multiclinsum_gs_en_520.txt
multiclinsum_gs_en_521.txt
multiclinsum_gs_en_522.txt
multiclinsum_gs_en_523.txt
multiclinsum_gs_en_524.txt
multiclinsum_gs_en_525.txt
multiclinsum_gs_en_526.txt
multiclinsum_gs_en_527.txt
multiclinsum_gs_en_528.txt
multiclinsum_gs_en_529.txt
multiclinsum_gs_en_53.txt
multiclinsum_gs_en_530.txt
multiclinsum_gs_en_531.txt
multiclinsum_gs_en_532.txt
multiclinsum_gs_en_533.txt
multiclinsum_gs_en_534.txt
multiclinsum_gs_en_535.txt
multiclinsum_gs_en_536.txt
multiclinsum_gs_en_537.txt
multiclinsum_gs_en_538.txt
multiclinsum_gs_en_539.txt
multiclinsum_gs_en_54.txt
multiclinsum_gs_en_540.txt
multiclinsum_gs_en_541.txt
multiclinsum_gs_en_542.txt
multiclinsum_gs_en_543.txt
multiclinsum_gs_en_544.txt
multiclinsum_gs_en_545.txt
multiclinsum_gs_en_546.txt
multiclinsum_gs_en_547.txt
multiclinsum_gs_en_548.txt
multiclinsum_gs_en_549.txt
multiclinsum_gs_en_55.txt
multiclinsum_gs_en_550.txt
multiclinsum_gs_en_551.txt
multiclinsum_gs_en_552.txt
multiclinsum_gs_en_553.txt
multiclinsum_gs_en_554.txt
multiclinsum_gs_en_555.txt
multiclinsum_gs_en_556.txt
multiclinsum_gs_en_557.txt
multiclinsum_gs_en_558.txt
multiclinsum_gs_en_559.txt
multiclinsum_gs_en_56.txt
multiclinsum_gs_en_560.txt
multiclinsum_gs_en_561.txt
multiclinsum_gs_en_562.txt
multiclinsum_gs_en_563.txt
multiclinsum_gs_en_564.txt
multiclinsum_gs_en_565.txt
multiclinsum_gs_en_566.txt
multiclinsum_gs_en_567.txt
multiclinsum_gs_en_568.txt
multiclinsum_gs_en_569.txt
multiclinsum_gs_en_57.txt
multiclinsum_gs_en_570.txt
multiclinsum_gs_en_571.txt
multiclinsum_gs_en_572.txt
multiclinsum_gs_en_573.txt
multiclinsum_gs_en_574.txt
multiclinsum_gs_en_575.txt
multiclinsum_gs_en_576.txt
multiclinsum_gs_en_577.txt
multiclinsum_gs_en_578.txt
multiclinsum_gs_en_579.txt
multiclinsum_gs_en_58.txt
multiclinsum_gs_en_580.txt
multiclinsum_gs_en_581.txt
multiclinsum_gs_en_582.txt
multiclinsum_gs_en_583.txt
multiclinsum_gs_en_584.txt
multiclinsum_gs_en_585.txt
multiclinsum_gs_en_586.txt
multiclinsum_gs_en_587.txt
multiclinsum_gs_en_588.txt
multiclinsum_gs_en_589.txt
multiclinsum_gs_en_59.txt
multiclinsum_gs_en_590.txt
multiclinsum_gs_en_591.txt
multiclinsum_gs_en_592.txt
multiclinsum_gs_en_6.txt
multiclinsum_gs_en_60.txt
multiclinsum_gs_en_61.txt
multiclinsum_gs_en_62.txt
multiclinsum_gs_en_63.txt
multiclinsum_gs_en_64.txt
multiclinsum_gs_en_65.txt
multiclinsum_gs_en_66.txt
multiclinsum_gs_en_67.txt
multiclinsum_gs_en_68.txt
multiclinsum_gs_en_69.txt
multiclinsum_gs_en_7.txt
multiclinsum_gs_en_70.txt
multiclinsum_gs_en_71.txt
multiclinsum_gs_en_72.txt
multiclinsum_gs_en_73.txt
multiclinsum_gs_en_74.txt
multiclinsum_gs_en_75.txt
multiclinsum_gs_en_76.txt
multiclinsum_gs_en_77.txt
multiclinsum_gs_en_78.txt
multiclinsum_gs_en_79.txt
multiclinsum_gs_en_8.txt
multiclinsum_gs_en_80.txt
multiclinsum_gs_en_81.txt
multiclinsum_gs_en_82.txt
multiclinsum_gs_en_83.txt
multiclinsum_gs_en_84.txt
multiclinsum_gs_en_85.txt
multiclinsum_gs_en_86.txt
multiclinsum_gs_en_87.txt
multiclinsum_gs_en_88.txt
multiclinsum_gs_en_89.txt
multiclinsum_gs_en_9.txt
multiclinsum_gs_en_90.txt
multiclinsum_gs_en_91.txt
multiclinsum_gs_en_92.txt
multiclinsum_gs_en_93.txt
multiclinsum_gs_en_94.txt
multiclinsum_gs_en_95.txt
multiclinsum_gs_en_96.txt
multiclinsum_gs_en_97.txt
multiclinsum_gs_en_98.txt
multiclinsum_gs_en_99.txt
multiclinsum_gs_en_100_sum.txt
multiclinsum_gs_en_101_sum.txt
multiclinsum_gs_en_102_sum.txt
multiclinsum_gs_en_103_sum.txt
multiclinsum_gs_en_104_sum.txt
multiclinsum_gs_en_105_sum.txt
multiclinsum_gs_en_106_sum.txt
multiclinsum_gs_en_107_sum.txt
multiclinsum_gs_en_108_sum.txt
multiclinsum_gs_en_109_sum.txt
multiclinsum_gs_en_10_sum.txt
multiclinsum_gs_en_110_sum.txt
multiclinsum_gs_en_111_sum.txt
multiclinsum_gs_en_112_sum.txt
multiclinsum_gs_en_113_sum.txt
multiclinsum_gs_en_114_sum.txt
multiclinsum_gs_en_115_sum.txt
multiclinsum_gs_en_116_sum.txt
multiclinsum_gs_en_117_sum.txt
multiclinsum_gs_en_118_sum.txt
multiclinsum_gs_en_119_sum.txt
multiclinsum_gs_en_11_sum.txt
multiclinsum_gs_en_120_sum.txt
multiclinsum_gs_en_121_sum.txt
multiclinsum_gs_en_122_sum.txt
multiclinsum_gs_en_123_sum.txt
multiclinsum_gs_en_124_sum.txt
multiclinsum_gs_en_125_sum.txt
multiclinsum_gs_en_126_sum.txt
multiclinsum_gs_en_127_sum.txt
multiclinsum_gs_en_128_sum.txt
multiclinsum_gs_en_129_sum.txt
multiclinsum_gs_en_12_sum.txt
multiclinsum_gs_en_130_sum.txt
multiclinsum_gs_en_131_sum.txt
multiclinsum_gs_en_132_sum.txt
multiclinsum_gs_en_133_sum.txt
multiclinsum_gs_en_134_sum.txt
multiclinsum_gs_en_135_sum.txt
multiclinsum_gs_en_136_sum.txt
multiclinsum_gs_en_137_sum.txt
multiclinsum_gs_en_138_sum.txt
multiclinsum_gs_en_139_sum.txt
multiclinsum_gs_en_13_sum.txt
multiclinsum_gs_en_140_sum.txt
multiclinsum_gs_en_141_sum.txt
multiclinsum_gs_en_142_sum.txt
multiclinsum_gs_en_143_sum.txt
multiclinsum_gs_en_144_sum.txt
multiclinsum_gs_en_145_sum.txt
multiclinsum_gs_en_146_sum.txt
multiclinsum_gs_en_147_sum.txt
multiclinsum_gs_en_148_sum.txt
multiclinsum_gs_en_149_sum.txt
multiclinsum_gs_en_14_sum.txt
multiclinsum_gs_en_150_sum.txt
multiclinsum_gs_en_151_sum.txt
multiclinsum_gs_en_152_sum.txt
multiclinsum_gs_en_153_sum.txt
multiclinsum_gs_en_154_sum.txt
multiclinsum_gs_en_155_sum.txt
multiclinsum_gs_en_156_sum.txt
multiclinsum_gs_en_157_sum.txt
multiclinsum_gs_en_158_sum.txt
multiclinsum_gs_en_159_sum.txt
multiclinsum_gs_en_15_sum.txt
multiclinsum_gs_en_160_sum.txt
multiclinsum_gs_en_161_sum.txt
multiclinsum_gs_en_162_sum.txt
multiclinsum_gs_en_163_sum.txt
multiclinsum_gs_en_164_sum.txt
multiclinsum_gs_en_165_sum.txt
multiclinsum_gs_en_166_sum.txt
multiclinsum_gs_en_167_sum.txt
multiclinsum_gs_en_168_sum.txt
multiclinsum_gs_en_169_sum.txt
multiclinsum_gs_en_16_sum.txt
multiclinsum_gs_en_170_sum.txt
multiclinsum_gs_en_171_sum.txt
multiclinsum_gs_en_172_sum.txt
multiclinsum_gs_en_173_sum.txt
multiclinsum_gs_en_174_sum.txt
multiclinsum_gs_en_175_sum.txt
multiclinsum_gs_en_176_sum.txt
multiclinsum_gs_en_177_sum.txt
multiclinsum_gs_en_178_sum.txt
multiclinsum_gs_en_179_sum.txt
multiclinsum_gs_en_17_sum.txt
multiclinsum_gs_en_180_sum.txt
multiclinsum_gs_en_181_sum.txt
multiclinsum_gs_en_182_sum.txt
multiclinsum_gs_en_183_sum.txt
multiclinsum_gs_en_184_sum.txt
multiclinsum_gs_en_185_sum.txt
multiclinsum_gs_en_186_sum.txt
multiclinsum_gs_en_187_sum.txt
multiclinsum_gs_en_188_sum.txt
multiclinsum_gs_en_189_sum.txt
multiclinsum_gs_en_18_sum.txt
multiclinsum_gs_en_190_sum.txt
multiclinsum_gs_en_191_sum.txt
multiclinsum_gs_en_192_sum.txt
multiclinsum_gs_en_193_sum.txt
multiclinsum_gs_en_194_sum.txt
multiclinsum_gs_en_195_sum.txt
multiclinsum_gs_en_196_sum.txt
multiclinsum_gs_en_197_sum.txt
multiclinsum_gs_en_198_sum.txt
multiclinsum_gs_en_199_sum.txt
multiclinsum_gs_en_19_sum.txt
multiclinsum_gs_en_1_sum.txt
multiclinsum_gs_en_200_sum.txt
multiclinsum_gs_en_201_sum.txt
multiclinsum_gs_en_202_sum.txt
multiclinsum_gs_en_203_sum.txt
multiclinsum_gs_en_204_sum.txt
multiclinsum_gs_en_205_sum.txt
multiclinsum_gs_en_206_sum.txt
multiclinsum_gs_en_207_sum.txt
multiclinsum_gs_en_208_sum.txt
multiclinsum_gs_en_209_sum.txt
multiclinsum_gs_en_20_sum.txt
multiclinsum_gs_en_210_sum.txt
multiclinsum_gs_en_211_sum.txt
multiclinsum_gs_en_212_sum.txt
multiclinsum_gs_en_213_sum.txt
multiclinsum_gs_en_214_sum.txt
multiclinsum_gs_en_215_sum.txt
multiclinsum_gs_en_216_sum.txt
multiclinsum_gs_en_217_sum.txt
multiclinsum_gs_en_218_sum.txt
multiclinsum_gs_en_219_sum.txt
multiclinsum_gs_en_21_sum.txt

In [27]:
import pandas as pd

df = pd.read_csv(r"..\Datasets\MultiClinSum\multiclinsum_dataset.csv")

In [28]:
df

,Unnamed: 0,complete_id,id,unique_id,language,quality,source,content,summary
0,0,1_en_gs,1,0,en,gs,multiclinsum,A 52-year-old female patient from Wolkiet (Nor...,A 52-year-old known female patient with a toxi...
1,1,1_en_ls,1,1,en,ls,multiclinsum,A healthy 53-year-old Japanese man experienced...,A 53-year-old Japanese man experienced sudden ...
2,2,2_en_gs,2,2,en,gs,multiclinsum,"35-year-old man, occupation: sandblaster for e...","We present the case of a 35-year-old man, a sa..."
3,3,2_en_ls,2,3,en,ls,multiclinsum,Written informed consent was obtained from the...,An ambulatory open inguinal herniorrhaphy was ...
4,4,3_en_gs,3,4,en,gs,multiclinsum,We present a case of a 59-year-old lady with a...,A 59-year-old woman was referred to the ophtha...
...,...,...,...,...,...,...,...,...,...
52983,52983,25898_fr_ls,25898,52983,fr,ls,multiclinsum,Un homme de 48 ans atteint d'ESKD a présenté u...,Nous décrivons un cas de neuropathie périphéri...
52984,52984,25899_fr_ls,25899,52984,fr,ls,multiclinsum,"Une femme caucasienne de 37 ans, auparavant en...",Une femme de 37 ans en bonne santé a présenté ...
52985,52985,25900_fr_ls,25900,52985,fr,ls,multiclinsum,Une Chinoise de 55 ans se présente avec une do...,Une Chinoise de 55 ans s'est présentée avec de...
52986,52986,25901_fr_ls,25901,52986,fr,ls,multiclinsum,La patiente était une fille de 3 mois née à 40...,La patiente dans ce cas était une fille de 3 m...
52987,52987,25902_fr_ls,25902,52987,fr,ls,multiclinsum,Une femme de 66 ans ayant des antécédents de D...,Une femme de 66 ans souffrant d'un choc septiq...

In [29]:
df["complete_id"] = (
    df["id"].astype(str) + "_" +
    df["language"] + "_" +
    df["quality"]
)
df

,Unnamed: 0,complete_id,id,unique_id,language,quality,source,content,summary
0,0,1_en_gs,1,0,en,gs,multiclinsum,A 52-year-old female patient from Wolkiet (Nor...,A 52-year-old known female patient with a toxi...
1,1,1_en_ls,1,1,en,ls,multiclinsum,A healthy 53-year-old Japanese man experienced...,A 53-year-old Japanese man experienced sudden ...
2,2,2_en_gs,2,2,en,gs,multiclinsum,"35-year-old man, occupation: sandblaster for e...","We present the case of a 35-year-old man, a sa..."
3,3,2_en_ls,2,3,en,ls,multiclinsum,Written informed consent was obtained from the...,An ambulatory open inguinal herniorrhaphy was ...
4,4,3_en_gs,3,4,en,gs,multiclinsum,We present a case of a 59-year-old lady with a...,A 59-year-old woman was referred to the ophtha...
...,...,...,...,...,...,...,...,...,...
52983,52983,25898_fr_ls,25898,52983,fr,ls,multiclinsum,Un homme de 48 ans atteint d'ESKD a présenté u...,Nous décrivons un cas de neuropathie périphéri...
52984,52984,25899_fr_ls,25899,52984,fr,ls,multiclinsum,"Une femme caucasienne de 37 ans, auparavant en...",Une femme de 37 ans en bonne santé a présenté ...
52985,52985,25900_fr_ls,25900,52985,fr,ls,multiclinsum,Une Chinoise de 55 ans se présente avec une do...,Une Chinoise de 55 ans s'est présentée avec de...
52986,52986,25901_fr_ls,25901,52986,fr,ls,multiclinsum,La patiente était une fille de 3 mois née à 40...,La patiente dans ce cas était une fille de 3 m...
52987,52987,25902_fr_ls,25902,52987,fr,ls,multiclinsum,Une femme de 66 ans ayant des antécédents de D...,Une femme de 66 ans souffrant d'un choc septiq...

In [30]:
summary_df = df[df["isSummary"] == True]
uns_df = df[df["isSummary"] == False]

KeyError: 'isSummary'

In [ ]:
summary_df

,Unnamed: 0,source,filetype,id,language,quality,isSummary,content,complete_id
592,592,multiclinsum,txt,100,en,gs,True,A six-month old infant presented to the emerge...,100_en_gs
593,593,multiclinsum,txt,101,en,gs,True,A 26-year-old male with no significant past me...,101_en_gs
594,594,multiclinsum,txt,102,en,gs,True,A 60-year-old woman with a history of presacra...,102_en_gs
595,595,multiclinsum,txt,103,en,gs,True,We describe the case of a 1-year-old girl with...,103_en_gs
596,596,multiclinsum,txt,104,en,gs,True,A 34-year-old female presented with a 5-day hi...,104_en_gs
...,...,...,...,...,...,...,...,...,...
105971,105971,multiclinsum,txt,9998,fr,ls,True,Nous rapportons le cas d'un homme de 73 ans ay...,9998_fr_ls
105972,105972,multiclinsum,txt,9999,fr,ls,True,La patiente était une femme de 44 ans qui souf...,9999_fr_ls
105973,105973,multiclinsum,txt,999,fr,ls,True,Une Chinoise de 66 ans s'est présentée à notre...,999_fr_ls
105974,105974,multiclinsum,txt,99,fr,ls,True,Un homme asiatique de 44 ans ayant des antécéd...,99_fr_ls
105975,105975,multiclinsum,txt,9,fr,ls,True,Une femme de 39 ans se plaignait principalemen...,9_fr_ls

In [ ]:
uns_df

,Unnamed: 0,source,filetype,id,language,quality,isSummary,content,complete_id
0,0,multiclinsum,txt,1,en,gs,False,A 52-year-old female patient from Wolkiet (Nor...,1_en_gs
1,1,multiclinsum,txt,10,en,gs,False,A 61-year-old patient with steroid therapy for...,10_en_gs
2,2,multiclinsum,txt,100,en,gs,False,A six-month-old male infant was observed in th...,100_en_gs
3,3,multiclinsum,txt,101,en,gs,False,"A male, 26 years old, was admitted to our hosp...",101_en_gs
4,4,multiclinsum,txt,102,en,gs,False,"60-year-old female, former smoker, overweight,...",102_en_gs
...,...,...,...,...,...,...,...,...,...
80069,80069,multiclinsum,txt,9995,fr,ls,False,"En janvier 2018, un patient de 58 ans a été ho...",9995_fr_ls
80070,80070,multiclinsum,txt,9996,fr,ls,False,"Une femme de 24 ans, primigeste, d'origine ind...",9996_fr_ls
80071,80071,multiclinsum,txt,9997,fr,ls,False,"En août 2015, une femme caucasienne de 46 ans ...",9997_fr_ls
80072,80072,multiclinsum,txt,9998,fr,ls,False,"Un homme de 73 ans souffrant de pneumoconiose,...",9998_fr_ls
80073,80073,multiclinsum,txt,9999,fr,ls,False,Une femme de 44 ans qui souffrait d'aménorrhée...,9999_fr_ls

In [ ]:
summary_map = summary_df.set_index("complete_id")["content"]

uns_df["summary"] = uns_df["complete_id"].map(summary_map)

In [ ]:
uns_df

,Unnamed: 0,source,filetype,id,language,quality,isSummary,content,complete_id,summary
0,0,multiclinsum,txt,1,en,gs,False,A 52-year-old female patient from Wolkiet (Nor...,1_en_gs,A 52-year-old known female patient with a toxi...
1,1,multiclinsum,txt,10,en,gs,False,A 61-year-old patient with steroid therapy for...,10_en_gs,This case report is about a 61-year-old patien...
2,2,multiclinsum,txt,100,en,gs,False,A six-month-old male infant was observed in th...,100_en_gs,A six-month old infant presented to the emerge...
3,3,multiclinsum,txt,101,en,gs,False,"A male, 26 years old, was admitted to our hosp...",101_en_gs,A 26-year-old male with no significant past me...
4,4,multiclinsum,txt,102,en,gs,False,"60-year-old female, former smoker, overweight,...",102_en_gs,A 60-year-old woman with a history of presacra...
...,...,...,...,...,...,...,...,...,...,...
80069,80069,multiclinsum,txt,9995,fr,ls,False,"En janvier 2018, un patient de 58 ans a été ho...",9995_fr_ls,Nous rapportons ici un cas qui est une illustr...
80070,80070,multiclinsum,txt,9996,fr,ls,False,"Une femme de 24 ans, primigeste, d'origine ind...",9996_fr_ls,Nous rapportons le cas d'une primigravide de 2...
80071,80071,multiclinsum,txt,9997,fr,ls,False,"En août 2015, une femme caucasienne de 46 ans ...",9997_fr_ls,Une femme caucasienne de 46 ans atteinte d'un ...
80072,80072,multiclinsum,txt,9998,fr,ls,False,"Un homme de 73 ans souffrant de pneumoconiose,...",9998_fr_ls,Nous rapportons le cas d'un homme de 73 ans ay...
80073,80073,multiclinsum,txt,9999,fr,ls,False,Une femme de 44 ans qui souffrait d'aménorrhée...,9999_fr_ls,La patiente était une femme de 44 ans qui souf...

In [ ]:
uns_df = uns_df[["complete_id", "id", "language", "quality", "source", "filetype", "content", "summary"]]
uns_df = uns_df.sort_values(by=["language", "id", "quality"])
uns_df = uns_df.reset_index(drop=True)
uns_df

,complete_id,id,language,quality,source,filetype,content,summary
0,1_en_gs,1,en,gs,multiclinsum,txt,A 52-year-old female patient from Wolkiet (Nor...,A 52-year-old known female patient with a toxi...
1,1_en_ls,1,en,ls,multiclinsum,txt,A healthy 53-year-old Japanese man experienced...,A 53-year-old Japanese man experienced sudden ...
2,2_en_gs,2,en,gs,multiclinsum,txt,"35-year-old man, occupation: sandblaster for e...","We present the case of a 35-year-old man, a sa..."
3,2_en_ls,2,en,ls,multiclinsum,txt,Written informed consent was obtained from the...,An ambulatory open inguinal herniorrhaphy was ...
4,3_en_gs,3,en,gs,multiclinsum,txt,We present a case of a 59-year-old lady with a...,A 59-year-old woman was referred to the ophtha...
...,...,...,...,...,...,...,...,...
52983,25898_fr_ls,25898,fr,ls,multiclinsum,txt,Un homme de 48 ans atteint d'ESKD a présenté u...,Nous décrivons un cas de neuropathie périphéri...
52984,25899_fr_ls,25899,fr,ls,multiclinsum,txt,"Une femme caucasienne de 37 ans, auparavant en...",Une femme de 37 ans en bonne santé a présenté ...
52985,25900_fr_ls,25900,fr,ls,multiclinsum,txt,Une Chinoise de 55 ans se présente avec une do...,Une Chinoise de 55 ans s'est présentée avec de...
52986,25901_fr_ls,25901,fr,ls,multiclinsum,txt,La patiente était une fille de 3 mois née à 40...,La patiente dans ce cas était une fille de 3 m...
52987,25902_fr_ls,25902,fr,ls,multiclinsum,txt,Une femme de 66 ans ayant des antécédents de D...,Une femme de 66 ans souffrant d'un choc septiq...

In [ ]:
print(uns_df[uns_df["filetype"] != "txt"].count())
uns_df = uns_df.drop(columns="filetype")
uns_df

complete_id    0
id             0
language       0
quality        0
source         0
filetype       0
content        0
summary        0
dtype: int64

,complete_id,id,language,quality,source,content,summary
0,1_en_gs,1,en,gs,multiclinsum,A 52-year-old female patient from Wolkiet (Nor...,A 52-year-old known female patient with a toxi...
1,1_en_ls,1,en,ls,multiclinsum,A healthy 53-year-old Japanese man experienced...,A 53-year-old Japanese man experienced sudden ...
2,2_en_gs,2,en,gs,multiclinsum,"35-year-old man, occupation: sandblaster for e...","We present the case of a 35-year-old man, a sa..."
3,2_en_ls,2,en,ls,multiclinsum,Written informed consent was obtained from the...,An ambulatory open inguinal herniorrhaphy was ...
4,3_en_gs,3,en,gs,multiclinsum,We present a case of a 59-year-old lady with a...,A 59-year-old woman was referred to the ophtha...
...,...,...,...,...,...,...,...
52983,25898_fr_ls,25898,fr,ls,multiclinsum,Un homme de 48 ans atteint d'ESKD a présenté u...,Nous décrivons un cas de neuropathie périphéri...
52984,25899_fr_ls,25899,fr,ls,multiclinsum,"Une femme caucasienne de 37 ans, auparavant en...",Une femme de 37 ans en bonne santé a présenté ...
52985,25900_fr_ls,25900,fr,ls,multiclinsum,Une Chinoise de 55 ans se présente avec une do...,Une Chinoise de 55 ans s'est présentée avec de...
52986,25901_fr_ls,25901,fr,ls,multiclinsum,La patiente était une fille de 3 mois née à 40...,La patiente dans ce cas était une fille de 3 m...
52987,25902_fr_ls,25902,fr,ls,multiclinsum,Une femme de 66 ans ayant des antécédents de D...,Une femme de 66 ans souffrant d'un choc septiq...

In [ ]:
uns_df["unique_id"] = range(uns_df.shape[0])
uns_df = uns_df[["complete_id", "id", "unique_id", "language", "quality", "source", "content", "summary"]]
uns_df

,complete_id,id,unique_id,language,quality,source,content,summary
0,1_en_gs,1,0,en,gs,multiclinsum,A 52-year-old female patient from Wolkiet (Nor...,A 52-year-old known female patient with a toxi...
1,1_en_ls,1,1,en,ls,multiclinsum,A healthy 53-year-old Japanese man experienced...,A 53-year-old Japanese man experienced sudden ...
2,2_en_gs,2,2,en,gs,multiclinsum,"35-year-old man, occupation: sandblaster for e...","We present the case of a 35-year-old man, a sa..."
3,2_en_ls,2,3,en,ls,multiclinsum,Written informed consent was obtained from the...,An ambulatory open inguinal herniorrhaphy was ...
4,3_en_gs,3,4,en,gs,multiclinsum,We present a case of a 59-year-old lady with a...,A 59-year-old woman was referred to the ophtha...
...,...,...,...,...,...,...,...,...
52983,25898_fr_ls,25898,52983,fr,ls,multiclinsum,Un homme de 48 ans atteint d'ESKD a présenté u...,Nous décrivons un cas de neuropathie périphéri...
52984,25899_fr_ls,25899,52984,fr,ls,multiclinsum,"Une femme caucasienne de 37 ans, auparavant en...",Une femme de 37 ans en bonne santé a présenté ...
52985,25900_fr_ls,25900,52985,fr,ls,multiclinsum,Une Chinoise de 55 ans se présente avec une do...,Une Chinoise de 55 ans s'est présentée avec de...
52986,25901_fr_ls,25901,52986,fr,ls,multiclinsum,La patiente était une fille de 3 mois née à 40...,La patiente dans ce cas était une fille de 3 m...
52987,25902_fr_ls,25902,52987,fr,ls,multiclinsum,Une femme de 66 ans ayant des antécédents de D...,Une femme de 66 ans souffrant d'un choc septiq...

In [ ]:
uns_df.to_csv(r"..\Datasets\MultiClinSum\multiclinsum_dataset.csv", index=True)